apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2020-01-23T16:38:28Z
  name: eleven-noi-objserv-agg-primary-config
  namespace: noi
data:
  agg-p-props-append: |
    MessageLevel: 'debug'
  agg-p-sql-extensions: | 
    -- create a custom db
    create database mydb; 
    go

    -- create a custom table        
    create table mydb.mytable persistent
    (
    col1 incr primary key,
    col2 varchar(255)
    );
    go
